name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  TIPTAP_PRO_TOKEN: ${{ secrets.TIPTAP_PRO_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
        with:
          ts: true
      - name: Install dependencies
        run: bun install
      - name: Build packages
        run: bun turbo run build --filter='./packages/*'
      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1.4.8
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: bun bump-versions
          publish: bun changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
